import { ActionIcon, Box, Center, Container, Paper, Space, Text, TextInput, Title, useMantineTheme } from '@mantine/core';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { IconPaint } from '@tabler/icons';
import ColorHash from 'color-hash';
import Head from 'next/head';
import { memo, useState } from 'react';
import { useAccount } from 'wagmi';

export default function Home() {
  const [color, setColor] = useState<string>("#fff");
  var colorHash = new ColorHash();
  const { address, isConnecting, isDisconnected } = useAccount()
  const addressInputClick = (address: string) => {
    setColor(colorHash.hex(address))
  }
  return (
    <div >
      <Head>
        <title>Address to Color</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ background: address && !isDisconnected ? colorHash.hex(address) : color }}>
        <Container>
          <Center style={{ height: "100vh" }}>
            <Box>
              <Center><Title>Address to <Text span c="blue" inherit>Color</Text></Title></Center>
              <Center><Text fz="xl" my={10} style={{ textAlign: "center" }}>Generates a specific color from an address</Text></Center>
              <Space h={30} />
              <AddressInput onClick={addressInputClick} />
              <Center fz={20} my={20}><Text>OR</Text></Center>
              <Center><ConnectButton chainStatus="none" showBalance={false} /></Center>
              {(address && !isDisconnected || color != "#fff") ?
                <Box my={30} p="md">
                  <Center><Title order={3}>Your Color</Title></Center>
                  <Center my={10}>{address && !isDisconnected ? colorHash.hex(address) : color}</Center>
                </Box>
                : <></>
              }
            </Box>
          </Center>
        </Container>
      </div>
    </div>
  )
}

const AddressInput: React.FC<{ onClick: (address: string) => void }> = memo(({ onClick }) => {
  const [inputAddress, setInputAddress] = useState("");
  const theme = useMantineTheme();
  return (<TextInput
    radius="xl"
    size="md"
    rightSection={
      <ActionIcon size={32} radius="xl" color={theme.primaryColor} variant="filled" onClick={() => { onClick(inputAddress) }}>
        {<IconPaint size={18} stroke={1.5} />}
      </ActionIcon>
    }
    placeholder="Wallet Address"
    rightSectionWidth={42}
    value={inputAddress}
    onChange={(e) => { setInputAddress(e.target.value) }}
  />)
})
